name: Model Retraining on Push to Main

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r Labs/Github_lab/requirements.txt

    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
      id: timestamp 

    - name: Check File Permissions
      run: |
        ls -l Labs/Github_lab/src/train_model.py

    - name: Set File Permissions
      run: |
        chmod +x Labs/Github_lab/src/train_model.py

    - name: Retrain Model
      run: |
        timestamp=$(cat timestamp.txt)
        cd Labs/Github_lab
        python src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt)
        cd Labs/Github_lab
        python src/evaluate_model.py --timestamp "$timestamp"
        metrics_filename="${timestamp}_metrics.json"
        mkdir -p metrics
        mv $metrics_filename metrics/$metrics_filename
      continue-on-error: false

    - name: Store and Version the New Model
      run: |
        timestamp=$(cat timestamp.txt)
        model_filename="model_${timestamp}_dt_model.joblib"
        cd Labs/Github_lab
        mkdir -p models
        mv $model_filename models/$model_filename

    - name: Commit and Push Changes
      run: |
        git config --global user.email "26876927+raminmohammadi@users.noreply.github.com"
        git config --global user.name "raminmohammadi"
        git add Labs/Github_lab/metrics/ Labs/Github_lab/models/
        git commit -m "Add metrics and updated model"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}